"""Added subnet_id, address unique key to quark_ip_addresses

Revision ID: 56326c29d553
Revises: 1817eef6373c
Create Date: 2014-06-04 15:44:27.611199

"""

# revision identifiers, used by Alembic.
revision = '56326c29d553'
down_revision = '1817eef6373c'

from alembic import op


def upgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'subnet_id_address',
        'quark_ip_addresses',
        ['subnet_id', 'address'])
    # end Alembic commands ###


def downgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subnet_id_address', 'quark_ip_addresses')
    # end Alembic commands ###
